name: Build Extension

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build_extension:
        name: Build Extension
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: "16"
                  cache: "npm"
            - name: Install Packages
              run: npm ci
            - name: Release
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, "refs/tags/")
              with:
                  files: |
                      build/hackbar_*.zip
